
package_assets: off

javascripts:
  common:
    - public/javascripts/base/mootools-core-1.3.js
    - public/javascripts/base/mootools-more.js
    - public/javascripts/base/*.js
  index:
    - public/javascripts/index/*.js
  sessions:
  registrations:
  invitations:
  posts:
  passwords: 
